---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
He thought he saw an Elephant    
That practised on a fife:    
He looked again, and found it was    
A letter from his wife.    
'At length I realize,' he said,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I craved strong sweets, but those    
Seemed strong when I was     
young;    
The petal of the rose   
It was that stung  .  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."   
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The first story I ever write    
is a bright crayon picture    
of a dancing tree, the branches    
tossed by island wind.    
  
I draw myself standing beside the tree,    
with a colorful parrot soaring above me,    
and a magical turtle clasped in my hand,    
and two yellow wings fluttering    
on the proud shoulders of my ruffled    
Cuban rumba dancer's    
fancy dress.    
    
In my California kindergarten class,    
the teacher scolds me: REAL TREES    
DON'T LOOK LIKE THAT.    
    
It's the moment    
when I first    
begin to learn   
that teachers    
can be wrong.    
    
They have never seen    
the dancing plants    
of Cuba.  